//
//  Generated by gentranslations.swift
//

final class Translation {

   enum Account: String {
      case email = "account.email"
      case name = "account.name"
      case signOut = "account.sign_out"
      case title = "account.title"
   }

   enum Alert: String {
      case confirm = "alert.confirm"
   }

   enum ContextMenu: String {
      case close = "context_menu.close"
      case copy = "context_menu.copy"
      case delete = "context_menu.delete"
      case edit = "context_menu.edit"
      case move = "context_menu.move"
      case rename = "context_menu.rename"
      case share = "context_menu.share"
   }

   enum Error: String {
      case accessTokenExpired = "error.access_token_expired"
      case `default` = "error.default"
      case title = "error.title"
   }

   enum Home: String {
      case title = "home.title"
   }

   enum Welcome: String {
      case email = "welcome.email"
      case password = "welcome.password"
      case signIn = "welcome.sign_in"
      case signUp = "welcome.sign_up"
      case subtitle = "welcome.subtitle"
      case title = "welcome.title"
   }

}
