//
//  Generated by gentranslations.swift
//

final class Translation {

   enum Welcome: String {
      case email = "welcome.email"
      case password = "welcome.password"
      case signIn = "welcome.sign_in"
      case signUp = "welcome.sign_up"
      case subtitle = "welcome.subtitle"
      case title = "welcome.title"
   }

}
