//
//  Generated by gentranslations.swift
//

final class Translation {

   enum Alert: String {
      case confirm = "alert.confirm"
   }

   enum Error: String {
      case accessTokenExpired = "error.access_token_expired"
      case `default` = "error.default"
      case title = "error.title"
   }

   enum Welcome: String {
      case email = "welcome.email"
      case password = "welcome.password"
      case signIn = "welcome.sign_in"
      case signUp = "welcome.sign_up"
      case subtitle = "welcome.subtitle"
      case title = "welcome.title"
   }

}
