openapi: 3.0.0
info:
  title: hApp JSON API
  version: 0.1.0
servers:
  - url: http://localhost:3000
    description: Your local machine.
paths:
  /accounts:
    post:
      tags:
        - Auth
      summary: Register a new account.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: John Appleseed
                email:
                  type: string
                  format: email
                  example: example@example.com
                password:
                  type: string
                  example: supersecret
      responses:
        201:
          description: Account created successfully if email was not taken.

